### ISSUE TITLE
Adding helloWorld to your resume is a GREAT idea!!!! 

### ISSUE THREAD

**Issue by 0SPwn** [roflsec1/x86assembly#1]
I'm just joking. Realistically, yes. You could. However, do you know enough low-level programming in those particular languages ASM, C etc to work as a dev in those languages? If you do, then, yes you can. However, if you're suffering from imposter syndrome and your work reflects that, you shouldn't.

**Comment by roflsec1** [comment]
Never actually ended up adding low-level development in my resume, I don't even do dev, thanks for your input though.
